Southern University of Science and Technology-Department of Computer Science and Engineering

Course: Machine Learning(CS 405)-Professor: Qi Hao

## Homework #2
#### Due date: October, 7th, 2019

In [1]:
"""
Import libraries that you might require.

"""

import numpy as np
import math
import matplotlib.pyplot as plt
import operator

from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier

In [2]:
from sklearn.datasets import load_breast_cancer

breast = load_breast_cancer()

X = breast['data']
y = breast['target']

np.random.seed(100)
p = np.random.permutation(len(X))
X, y = X[p], y[p]

X_train, y_train = X[:400], y[:400]
X_val, y_val = X[400:500], y[400:500]
X_test, y_test = X[500:], y[500:]


In [21]:
X.shape[0]
len(X)
y
type(X[[1,2]])
X[0,0]

17.91

In [40]:
import numpy as np
x = [2,-1,-1,-1]
x = np.square(x)
x
X_train[:,1]
for i,item in enumerate(X_train):
    for j,item in enumerate(X_train[i,:]):
        neighbors = j
neighbors
len(X_train[1,:])

30

We will implement the KNN algorithm for the breast cancer dataset. Refer to the pdf and the following functions for the instructions. Complete all the functions as indicated below. The four functions would be autograded as mentioned in the pdf.

The L1 norm that is calculated as the sum of the absolute values of the vector.  
The L2 norm that is calculated as the square root of the sum of the squared vector values.  
The max norm that is calculated as the maximum vector values.  

In [64]:
neighbors = computeDistancesNeighbors(1, "L2", X_train, y_train, 1)

In [7]:
X = np.array([[1,2,3],[1,3,6]])
y = np.array([1,0])
X

array([[1, 2, 3],
       [1, 3, 6]])

In [10]:

neighbors = computeDistancesNeighbors(1, "L2", X, y, 1)
len(neighbors)

36

In [60]:
two_d = np.array([[1, 2], [4, 5]])
# for x,y in X_val:
#     pass

# print(type(X_train))
# type(two_d)

ValueError: too many values to unpack (expected 2)

In [3]:
"""
Task 1: Classification

Please implement KNN for K: 3, 5, and 7 with the following norms:
L1
L2
L-inf
"""

# Read data (Breast Cancer Dataset). Remember to comment out the code not contained in a function.
from sklearn.datasets import load_breast_cancer

breast = load_breast_cancer()

X = breast['data']
y = breast['target']

np.random.seed(100)
p = np.random.permutation(len(X))
X, y = X[p], y[p]

X_train, y_train = X[:400], y[:400]
X_val, y_val = X[400:500], y[400:500]
X_test, y_test = X[500:], y[500:]


def distanceFunc(metric_type, vec1, vec2):
    """
    Computes the distance between two d-dimension vectors. 
    
    Please DO NOT use Numpy's norm function when implementing this function. 
    
    Args:
        metric_type (str): Metric: L1, L2, or L-inf
        vec1 ((d,) np.ndarray): d-dim vector
        vec2 ((d,)) np.ndarray): d-dim vector
    
    Returns:
        distance (float): distance between the two vectors
    """
    diff = vec1 - vec2
    #diff = list(diff)
    if metric_type == "L1":
        diff_abs = np.abs(diff)
        distance = np.sum(diff_abs) #complete

    if metric_type == "L2":
        diff_square = np.square(diff)
        distance = np.sqrt(np.sum(diff_square)) #complete
        
    if metric_type == "L-inf":
        diff_abs = np.abs(diff)
        distance = np.max(diff_abs) #complete
        
    return distance


def computeDistancesNeighbors(K, metric_type, X_train, y_train, sample):
    """
    Compute the distances between every datapoint in the train_data and the 
    given sample. Then, find the k-nearest neighbors.
    
    Return a numpy array of the label of the k-nearest neighbors.
    
    Args:
        K (int): K-value
        metric_type (str): metric type
        X_train ((n,p) np.ndarray): Training data with n samples and p features
        y_train : Training labels
        sample ((p,) np.ndarray): Single sample whose distance is to computed with every entry in the dataset
        
    Returns:
        neighbors (list): K-nearest neighbors' labels
    """

    # You will also call the function "distanceFunc" here
    # Complete this function
    neighbors = []
    for i,item in enumerate(X_train):
        for j,item in enumerate(X_train[i,:]):
            for i_k,item in enumerate(X_train):
                for j_k,item in enumerate(X_train[i,:]):
                    vec1 = X_train[i,j]
                    vec2 = X_train[i_k,j_k]
                    neighbors.append(distanceFunc("L1", vec1, vec2))
    return neighbors


def Majority(neighbors):
    """
    Performs majority voting and returns the predicted value for the test sample.
    
    Since we're performing binary classification the possible values are [0,1].
    
    Args:
        neighbors (list): K-nearest neighbors' labels
        
    Returns:
        predicted_value (int): predicted label for the given sample
    """
    
    # Performs majority voting
    # Complete this function

    
    
    return predicted_value


def KNN(K, metric_type, X_train, y_train, X_val):
    """
    Returns the predicted values for the entire validation or test set.
    
    Please DO NOT use Scikit's KNN model when implementing this function. 

    Args:
        K (int): K-value
        metric_type (str): metric type
        X_train ((n,p) np.ndarray): Training data with n samples and p features
        y_train : Training labels
        X_val ((n, p) np.ndarray): Validation or test data
        
    Returns:
        predicted_values (list): output for every entry in validation/test dataset 
    """
    
    # Complete this function
    # Loop through the val_data or the test_data (as required)
    # and compute the output for every entry in that dataset  
    # You will also call the function "Majority" here

    return predictions


def evaluation(predicted_values, actual_values):
    """
    Computes the accuracy of the given datapoints.
    
    Args:
        predicted_values ((n,) np.ndarray): Predicted values for n samples
        actual_values ((n,) np.ndarray): Actual values for n samples
    
    Returns:
        accuracy (float): accuracy
    """
    
    return accuracy_score(predicted_values, actual_values)


def main():
    """
    Calls the above functions in order to implement the KNN algorithm.
    
    Test over the following range K = 3,5,7 and all three metrics. 
    In total you will have nine combinations to try.
    
    PRINTS out the accuracies for the nine combinations on the validation set,
    and the accuracy on the test set for the selected K value and appropriate norm.
    
    REMEMBER: You have to report these values by populating the Table 1.
    """
    
    ## Complete this function
    
    K = [3,5,7]
    norm = ["L1", "L2", "L-inf"]
    
    print("<<<<VALIDATION DATA PREDICTIONS>>>>")
    
    ## Complete
    
    print("<<<<TEST DATA PREDICTIONS>>>>")
    
    ## Complete

In [7]:
class KNNClassfier(object):

    def __init__(self, k=5, distance='euc'):
        self.k = k
        self.distance = distance
        self.x = None
        self.y = None
        
    def fit(self,X, Y):
        '''
        X : array-like [n_samples,shape]
        Y : array-like [n_samples,1]
        '''        
        self.x = X
        self.y = Y

    def predict(self,X_test):
        '''
        X_test : array-like [n_samples,shape]
        Y_test : array-like [n_samples,1]
        output : array-like [n_samples,1]
        '''  
        all_dis = []
        output = np.zeros((X_test.shape[0],1))
        for i in range(X_test.shape[0]):
            dis = [] 
            for j in range(self.x.shape[0]):
                if self.distance == 'euc': # 欧式距离
                    dis.append(np.linalg.norm(X_test[i,:]-self.x[j,:]))
            all_dis.append(dis)

            labels = []
            index=sorted(range(len(dis)), key=dis.__getitem__)
            for j in range(self.k):
                labels.append(self.y[index[j]])
            print(labels)

            counts = []
            for label in labels:
                counts.append(labels.count(label))


            output[i] = labels[np.argmax(counts)]
        print(len(dis))
        print(len(X_test))
        return output,all_dis
    

    def score(self,pred,y):
       # pred = self.predict(x)
        err = 0.0
        for i in range(y.shape[0]):
            if pred[i]!=y[i]:
                err = err+1
        return 1-float(err/y.shape[0])


In [8]:
clf = KNNClassfier(k=3)
clf.fit(X_train,y_train)
pred,all_dis = clf.predict(X_test)
clf.score(pred,y_test)


[1, 1, 1]
[1, 1, 1]
[1, 1, 1]
[0, 0, 0]
[0, 0, 0]
[1, 1, 1]
[0, 0, 0]
[1, 1, 1]
[1, 1, 1]
[1, 1, 1]
[0, 0, 0]
[1, 0, 1]
[1, 1, 1]
[1, 0, 1]
[0, 0, 0]
[1, 1, 1]
[1, 1, 0]
[1, 1, 1]
[1, 1, 0]
[1, 1, 1]
[0, 0, 0]
[0, 0, 0]
[1, 1, 1]
[0, 0, 0]
[1, 1, 1]
[0, 1, 1]
[0, 0, 0]
[1, 1, 1]
[1, 1, 1]
[1, 1, 1]
[1, 1, 1]
[0, 0, 0]
[0, 0, 0]
[0, 0, 0]
[1, 1, 1]
[1, 1, 1]
[1, 1, 0]
[1, 1, 1]
[0, 0, 0]
[0, 0, 0]
[1, 1, 1]
[0, 0, 0]
[0, 1, 0]
[1, 0, 0]
[0, 0, 0]
[1, 1, 1]
[1, 1, 1]
[1, 1, 1]
[0, 0, 0]
[1, 1, 1]
[0, 0, 0]
[1, 1, 1]
[1, 1, 1]
[1, 1, 1]
[0, 0, 0]
[0, 0, 0]
[1, 1, 1]
[1, 1, 1]
[1, 1, 0]
[1, 1, 1]
[1, 1, 1]
[1, 1, 1]
[1, 1, 1]
[0, 0, 0]
[1, 1, 0]
[0, 0, 0]
[1, 1, 1]
[1, 1, 1]
[1, 1, 1]
400
69


0.8840579710144928

Uncomment the code below to run the main function (Remember to recomment the code before submitting).

In [53]:
# Finally, call the main function
# main()
len(all_dis)
len(X_train)
print(X_train.shape[:])
print(X_test.shape[:])
all_dis = np.array(all_dis)
print(all_dis.shape[:])
all_dis[68,:]

(400, 30)
(69, 30)
(69, 400)


array([1228.39208106,  670.46728057, 1678.64724855,  134.97344493,
        273.08293162,  198.39168617, 1187.48913703, 1838.495648  ,
        555.06220441,  273.20982015,   28.30869937, 1533.80090613,
       3324.63776691, 1885.2524455 ,  484.80500112,  791.76149519,
        840.3141892 ,  453.89104138,   55.19565703,  226.46160004,
        943.95468909,  360.91255365,  832.47829574, 2362.78435718,
        594.12647647, 1024.48974181,  247.67154161,   54.97361601,
        252.3288563 ,  302.61341068,  221.2910329 ,  257.8388386 ,
        520.00817743, 1084.93719096, 1637.89774871,  225.70579985,
        400.24194219,  388.0052338 ,  133.54274062, 2398.21623951,
        816.57090389,  309.15416951,  136.17050514,  739.13104067,
        517.91786661,  897.26347485,  188.82888323,   27.56218187,
        224.63585694,   15.60243596,  832.63435619,   35.85542896,
        612.70571858, 1098.7813116 ,  250.40604248,  499.95360801,
        472.6615807 ,  275.79638752,   75.18304173,  237.29722

In [59]:
diff = X_test[1,:]-X_train[1,:]
diff_square = np.square(diff)
distance = np.sqrt(np.sum(diff_square))

distance
distance2 = np.linalg.norm(X_test[1,:]-X_train[1,:])
print(distance)
print(distance2)

483.64673633137875
483.64673633137875


In [51]:
for i in range(X_test.shape[0]):
    dis = [] 
    for j in range(X_train.shape[0]):
        # dis.append(np.linalg.norm(X_test[i,:]-X_train[j,:]))
        diff = X_test[i,:]-X_train[j,:]
        diff_square = np.square(diff)
        distance = np.sqrt(np.sum(diff_abs))

    #all_dis.append(dis)

[1228.3920810612967,
 670.4672805671959,
 1678.6472485492206,
 134.9734449305453,
 273.0829316178607,
 198.3916861711877,
 1187.4891370257158,
 1838.4956480048447,
 555.0622044111343,
 273.2098201510702,
 28.308699373654125,
 1533.8009061341074,
 3324.6377669055328,
 1885.2524454969173,
 484.8050011209675,
 791.7614951892691,
 840.3141891968595,
 453.8910413758823,
 55.1956570317644,
 226.46160004003997,
 943.9546890883832,
 360.91255365183883,
 832.4782957417731,
 2362.7843571766866,
 594.1264764664473,
 1024.4897418058852,
 247.67154161280672,
 54.973616014463786,
 252.32885629893084,
 302.61341067970943,
 221.29103290113477,
 257.8388385954318,
 520.0081774256548,
 1084.9371909590309,
 1637.897748714578,
 225.7057998514512,
 400.241942192181,
 388.0052337966568,
 133.54274061519948,
 2398.2162395143814,
 816.5709038865108,
 309.15416950606044,
 136.17050513712016,
 739.1310406719138,
 517.9178666098818,
 897.2634748504563,
 188.82888323372245,
 27.562181871414477,
 224.6358569386266

Answer the following questions here:

1. How could having a larger dataset influence the performance of KNN?

2. Tabulate your results from `main()` in the table provided.

3. Finally, mention the best K and the norm combination you have settled upon and report the accuracy on the test set using that combination.

Test

In [11]:
def distanceFunc(metric_type, vec1, vec2):
    """
    Computes the distance between two d-dimension vectors. 
    
    Please DO NOT use Numpy's norm function when implementing this function. 
    
    Args:
        metric_type (str): Metric: L1, L2, or L-inf
        vec1 ((d,) np.ndarray): d-dim vector
        vec2 ((d,)) np.ndarray): d-dim vector
    
    Returns:
        distance (float): distance between the two vectors
    """
    diff = vec1 - vec2
    #diff = list(diff)
    if metric_type == "L1":
        diff_abs = np.abs(diff)
        distance = np.sum(diff_abs) #complete

    if metric_type == "L2":
        diff_square = np.square(diff)
        distance = np.sqrt(np.sum(diff_square)) #complete
        
    if metric_type == "L-inf":
        diff_abs = np.abs(diff)
        distance = np.max(diff_abs) #complete
        
    return distance

In [88]:
X = np.array([[1,9,3],[1,3,6],[5,5,5],[7,7,8]])
y = np.array([1,0,1,1])
distance1 = []
distance2 = []
len_X = X.shape[0]
X_idx = X
output = np.zeros((X.shape[0],1))
for i in range(len_X):
    dis = []
    for j in (range(len_X)):
        dis1 = np.linalg.norm(X[i,:]-X_idx[(j),:])
        dis.append(dis1)
    #print(dis)

    labels = []
    index=sorted(range(len(dis)), key=dis.__getitem__)


    labels = []
    for j in range(3):
        labels.append(y[index[j]])
    

    counts = []
    for label in labels:
        counts.append(labels.count(label))
    output[i] = labels[np.argmax(counts)]
print(output)
        



    
#print(dis)

# for i,item in enumerate(X):
#     for j,item in enumerate(X[i]):
#         for i_k,item in enumerate(X):
#             for j_k,item in enumerate(X[i_k]):
#                 vec1 = X[i][j]
#                 vec2 = X[i_k][j_k]
#                 distance1.append(distanceFunc("L1", vec1, vec2))
                #distance2.append(np.linalg.norm(vec1,vec2))
# distanceFunc("L1", vec1, vec2)
# np.linalg.norm

[[1.]
 [1.]
 [1.]
 [1.]]


In [85]:
#dis = [6.0, 4.58257569495584, 0.0, 4.123105625617661]
# dis = [20,16,12,13]
labels


[1, 1, 0]

In [72]:
range(len(dis))

range(0, 4)

In [81]:



output








[1, 1, 0]


[1]

In [79]:
students = [10,20,30]
newgrades = [4,2,3]
sorted(students, key=newgrades.__getitem__)

IndexError: list index out of range

In [21]:
X[1][1] - X[0][0]
np.linalg.norm(vec1-vec2)

0.0

In [27]:
from sklearn import datasets
iris = datasets.load_iris()
x = iris.data
y = iris.target
x.shape[:]

(150, 4)

In [29]:
x[1,:]

array([4.9, 3. , 1.4, 0.2])

In [30]:
X_train.shape[:]

(400, 30)